### PR TITLE
Add update_user_password to SecurityService

### LINKED ISSUE #412: Function for update password
Could we add a function to specifically update just the password for a user.

### PR DESCRIPTION
**Pull request by MariusWirtz**
Fixes #412

### CODE REVIEW

**Comment by MariusWirtz** [comment]
Hi @scrumthing,

is this what you had in mind?
You can upgrade to the branch with pip like this:
`pip install https://github.com/cubewise-code/tm1py/archive/feature/update-password.zip --upgrade`

**Comment by scrumthing** [comment]
Looks good. Will test it next week. :-)

**Comment by scrumthing** [comment]
Just to be thorough. Tested it and worked perfect.

**Comment by MariusWirtz** [comment]
Thanks. Appreciate the feedback.

**Pull request merged**
