### PR TITLE
Feature/v12

### PR DESCRIPTION
**Pull request by MariusWirtz**
v12 feature branch based on https://github.com/rclapp/TM1py/tree/tm1-v12-ga-release-testing
Adapted to work with TM1 v12 in IBM Cloud (PaaS).

``` python
from TM1py import TM1Service

with TM1Service(
        address="us-east-2.aws.planninganalytics.ibm.com",
        api_key="AB4VfG7T8wPM-912uFKeYG5PGh0XbS80MVBAt7SEG6xn",
        iam_url="https://iam.cloud.ibm.com/identity/token",
        tenant="YA9A2T8BS2ZU",
        database="CWRecordsMDX") as tm1:

    print(tm1.dimensions.get_all_names())
```

### CODE REVIEW

**Comment by MariusWirtz** [comment]
@rclapp, @janus-t, @Wuzardor,
This could be a good base for further collaboration.

This Pull Request contains all commits from Ryan's branch but is rebased on the current master and contains one additional commit to adapt the branch for PAaaS: https://github.com/cubewise-code/tm1py/pull/1000/commits/608cdca5f0d0f231dd43f654a1a22d2c0a9056e5

Above is an example of how you can use the branch with PAaaS in the IBM Cloud.


@rclapp 
I am still trying to figure out the new terminology. Possibly the `tenant` and `instance` are actually the same thing?

I limited my changes to the `RestService` for now, but I might have accidentally broken the authentication mode you implemented for local v12. Could you please verify if it still works? I haven't arranged my access to local v12 yet.

I introduced an enum in the `RestService` to separate the different authentication modes more clearly.
There might be more synergies between the two authentication modes that we implemented. 
I called mine `IBM_CLOUD_API_KEY` and yours `CP4D`. I am not sure about those names TBH.

Now I will do more testing and try to make things pretty and name things more appropriately.

**Comment by rclapp** [comment]
Sounds goods I will be testing on the latest release next week

On Dec 1, 2023 10:41 AM, Marius Wirtz ***@***.***> wrote:

v12 feature branch based on https://github.com/rclapp/TM1py/tree/tm1-v12-ga-release-testing
Adapted to work with TM1 v12 in IBM Cloud (PaaS).

from TM1py import TM1Service

with TM1Service(
        address="us-east-2.aws.planninganalytics.ibm.com",
        api_key="AB4VfG7T8wPM-912uFKeYG5PGh0XbS80MVBAt7SEG6xn",
        iam_url="https://iam.cloud.ibm.com",
        tenant="YA9A2T8BS2ZU",
        database="CWRecordsMDX") as tm1:

    print(tm1.dimensions.get_all_names())

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/cubewise-code/tm1py/pull/1000

Commit Summary

  *   ada19d8<https://github.com/cubewise-code/tm1py/pull/1000/commits/ada19d8c5f9405c5500f5f0b1f2cb0d2eafdb599> Update test case to correct element order in assert
  *   66439a4<https://github.com/cubewise-code/tm1py/pull/1000/commits/66439a4b1c1d24fa62019ff5eabd6b28d9ce64c0> Tm1 v12 support service url (#2)
  *   ca66d43<https://github.com/cubewise-code/tm1py/pull/1000/commits/ca66d437c65699ac4ee89b940db04e99afed025a> Updates to trace and check tests.
  *   5168975<https://github.com/cubewise-code/tm1py/pull/1000/commits/51689759a974f062d460ef536d774d18992b03d1> Fix to account for major versions lack of fixes
  *   a5a6cca<https://github.com/cubewise-code/tm1py/pull/1000/commits/a5a6cca50232203078c3756a0005aa5661d10b66> Element Service update for BI
  *   12a7ccc<https://github.com/cubewise-code/tm1py/pull/1000/commits/12a7ccc7ae85867434f2ef7f1cabcabc3ac2786e> Updates to support v12. Mostly changes to MDX syntax
  *   6d45ac9<https://github.com/cubewise-code/tm1py/pull/1000/commits/6d45ac9493506239884412c35044f46d5c7b1711> Updates to support power bi service and the changes to supported MDX
  *   ba6eeb9<https://github.com/cubewise-code/tm1py/pull/1000/commits/ba6eeb93685cea7ff8a2de9636e5374d5fc1a28e> Updates to process tests to correct processes syntax
  *   a9b54f2<https://github.com/cubewise-code/tm1py/pull/1000/commits/a9b54f20433b2c8fd5e9ea76a349fb4cdd92b532> Update tests to use new integer format
  *   b715e88<https://github.com/cubewise-code/tm1py/pull/1000/commits/b715e88fd4aa33c68efbccf95740455225f0a742> Updates to support v11 MDX formats.
  *   fb58a6c<https://github.com/cubewise-code/tm1py/pull/1000/commits/fb58a6c24802f6f4512f8922fca57da774b3bb7c> Corrected issue with admin host servers
  *   55e20ca<https://github.com/cubewise-code/tm1py/pull/1000/commits/55e20cab3da80bcbf7451ac31329152c3f324600> Corrected issue with admin host servers
  *   d1416c4<https://github.com/cubewise-code/tm1py/pull/1000/commits/d1416c4badd24577a7cea755dbc1e23988d79595> Cookie processing update, changes to URL generation to prevent trailing &
  *   c0df8af<https://github.com/cubewise-code/tm1py/pull/1000/commits/c0df8af3e5628b8f232f641fab1dd19269460b4e> Small change from a warning to an exception so that issues don't go missing.
  *   9581d38<https://github.com/cubewise-code/tm1py/pull/1000/commits/9581d38f48813e7b682debdffddf764e66cd7107> Skip tests that are no longer supported in v12
  *   d9252ab<https://github.com/cubewise-code/tm1py/pull/1000/commits/d9252ab1cc6d81932c9eea4b6271bb0871e055df> Compact json update for new v12 format
  *   23a38bc<https://github.com/cubewise-code/tm1py/pull/1000/commits/23a38bcaad6a195aa6a056bb41c7f15023420390> Changed to MDXpy to correct subset creation errors
  *   7cfe2b5<https://github.com/cubewise-code/tm1py/pull/1000/commits/7cfe2b50c074a67d55c153e1eb21a7dbcba7fc7e> Fix for numeric attributes in tests
  *   939d206<https://github.com/cubewise-code/tm1py/pull/1000/commits/939d206915945160c82e45458996dce37df53e5d> Deprecated Threads endpoints
  *   06a7c27<https://github.com/cubewise-code/tm1py/pull/1000/commits/06a7c27e9988aa0be2c4412db615e500128d1cf9> Deprecated Threads endpoints
  *   c780281<https://github.com/cubewise-code/tm1py/pull/1000/commits/c780281a6a0c28a49e17831ec380beb0d494f225> Deprecated Threads endpoints
  *   f111235<https://github.com/cubewise-code/tm1py/pull/1000/commits/f11123534676e175f9bad4bbc11ae84598b813ed> Deprecate Server methods
  *   608cdca<https://github.com/cubewise-code/tm1py/pull/1000/commits/608cdca5f0d0f231dd43f654a1a22d2c0a9056e5> Adapt v12 branch to PAaaS

File Changes

(41 files<https://github.com/cubewise-code/tm1py/pull/1000/files>)

  *   M TM1py/Exceptions/Exceptions.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-5e5271de0f1e8b3de3679d5605d8c5e7dfaccc82930fe8ac4138ac941da7b358> (9)
  *   M TM1py/Objects/Chore.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-fe67df19c1e99fb2bd67ca544275eedfb673af25ed39fdb25c88525ca41e48d1> (2)
  *   M TM1py/Objects/GitProject.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-ff2cced22b560645aa7c5429c92fc6890f3bb0fd61ee3acb2ac92ec0b25a7cc8> (2)
  *   M TM1py/Objects/Process.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-b2cc6ea9df8fae2edd2e8e71fc8b5fcbad16792e8f276302c79ddb559a1367ba> (2)
  *   M TM1py/Objects/Server.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-a4de3ddf6f6f47f753b850eb3b6b4be2865fc1d5ac5dd4276024a5d46d04029c> (2)
  *   M TM1py/Objects/User.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-f1a30d2643cac51e81a6f34c4fa2b1c1a9501f2bc6e6db39efc7130cda7baedc> (2)
  *   M TM1py/Services/AnnotationService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-21444f476954faf45029b5825698c0596135589bdc90a884fb5271eaffaa7cee> (12)
  *   M TM1py/Services/ApplicationService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-ff5034880f13955caa59612bc86ef2c6ba41fbb9317be3e1c719c3b0576da3d2> (50)
  *   M TM1py/Services/CellService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-5242c6c19161de7f529a4e5b0d0b33ca9c15f69be65fa5409881b3d8310ff655> (67)
  *   M TM1py/Services/ChoreService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-ec32a3e9816edfdafcf2dd76743fd896210577c65590d7bfb1cfa4474507cf8f> (36)
  *   M TM1py/Services/CubeService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-ec6cb09a1a804625499acc177bac30c1123f0e160280e84642c6fbdc0491345e> (52)
  *   M TM1py/Services/DimensionService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-1a7dea553c079856a087281a10efb73d92d095e1ac6f5f1d2da4b9ad2bbd9034> (16)
  *   M TM1py/Services/ElementService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-e7f25d4b50d2e3acec4039248316ad6415f34024d92ec6c124aeb2e500cd2214> (197)
  *   M TM1py/Services/FileService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-128ba8c1f314f987543ca4a5dd94786a57a57cd616f0fd74565d2da92718a7af> (43)
  *   M TM1py/Services/GitService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-fdd8913eabb51db4d359f2a36c3497a79f11f1ab444b0cbdfad5e73d8452208e> (20)
  *   M TM1py/Services/HierarchyService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-ba50c386d64307c2aeb9c04a92e6b646e1b1550c4f2d721e2529e1eb130a8224> (60)
  *   A TM1py/Services/ManageService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-8892bd7528e3030d1e72ad7f76e58b919bb2f117f828f7aef1cd7bc31b3e6004> (161)
  *   M TM1py/Services/MonitoringService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-ac631bc9995e86856a4a976769b2e4af1681390bd2af115f19dd61ec4a3c9c2b> (26)
  *   M TM1py/Services/ObjectService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-8960d58bef9590da2fa38d1b7418253f3845ed33a7912a0e261f3c6465145776> (2)
  *   M TM1py/Services/ProcessService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-4becc31e01a64735d1b995598126ae48d9e206262caa16f009f8e2b4b7fdc471> (76)
  *   M TM1py/Services/RestService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-df14b1ce4521159bb1d052572bc5c8a829dd9a0680e61212100d7b1df2f5f8ab> (403)
  *   M TM1py/Services/SandboxService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-86d2b7551ca1e5eb6de6605a49ae5265097df3b34c157b2f332aac6df5b06a7b> (24)
  *   M TM1py/Services/SecurityService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-9bec92cf8b46e35518719c724bbf4c5a3149696794fda710c172ab765ed29c13> (36)
  *   M TM1py/Services/ServerService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-34bba3918e81eead6084c8dd8ba01f378382f2a1833e38a4f712189d9801d948> (95)
  *   M TM1py/Services/SubsetService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-35145fbea5f1149d194fe674263edc2d18c55e0259965ab8c1d941f3111c706c> (16)
  *   M TM1py/Services/ViewService.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-2edf9bf37415f72f25158e4fcd9421f0717145b78517c208c6c4c5c96170d902> (24)
  *   M TM1py/Services/__init__.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-f04bb968c4557a8530922e418a6a403e74e0f47f07df2fa70752a7716225b9ac> (1)
  *   M TM1py/Utils/Utils.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-dfa6efa267891cf338ac4ae2fb7d41b941f6ecef55b265005ff460b33c9e8f9d> (32)
  *   M TM1py/__init__.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-afe2a317ed48acce535c923a91437c4cfc916e7d1d78f91ad938cafadad13693> (1)
  *   M Tests/ApplicationService_test.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-09f6740132c6b1050d3b1aecc6da7e137ed42bbe3fbb77edd464929cd02da651> (18)
  *   M Tests/CellService_test.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-d044783f3dd2a3bc2510c242076847e316dd0ce57d3724cc09870fcca88f5e2d> (101)
  *   M Tests/CubeService_test.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-14363e18c9562e18c439889373ab8865e5f1399a961666c9c9263a990daa5b1d> (14)
  *   M Tests/HierarchyService_test.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-a4c2e2438b3c3eba25223222870a46d0d052abae551914144bed4f61816bdd77> (5)
  *   M Tests/MonitoringService_test.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-97641823b965af4507440e6d2ea214514a655864b7f37005365984e770b163ab> (7)
  *   M Tests/ProcessService_test.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-13f526818f47c0061029832f46e9d8ccf9e1ab29a1d6b37b05c7065035746b22> (76)
  *   M Tests/SandboxService_test.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-76c9a68cbd13208708199405d14b82d530f269b060a373736763d0d9bffb9670> (4)
  *   M Tests/SecurityService_test.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-f35e9f0ddfc55ef496a2776279465145cb581bf6704de57d874ea548c87814e8> (27)
  *   M Tests/ServerService_test.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-b4847be431dc2335ae4ae05cc1db3a62b49cb9f2cc9e156de6ba24162b57f61c> (4)
  *   M Tests/Utils.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-1b794e8fb17fa110623a38255f62bd3c26abba0997a6bc00e1ca4c58afabfbdd> (22)
  *   M Tests/Utils_test.py<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-5b9a97d81121f9d05bb177487fd4ef7aa13ee70000bef7eb7c175c575a42f302> (50)
  *   M Tests/config.ini<https://github.com/cubewise-code/tm1py/pull/1000/files#diff-f4d28f806fc3e7b44475f9e54ab081584c3ee124174f5255c1543868acce491e> (20)

Patch Links:

  *   https://github.com/cubewise-code/tm1py/pull/1000.patch
  *   https://github.com/cubewise-code/tm1py/pull/1000.diff

**Comment by MariusWirtz** [comment]
@Wuzardor,

Thanks for the background on the tenant vs instance concepts.

You can upgrade your local TM1py to this branch with the pip statement below.

```
pip uninstall tm1py
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/feature/v12.zip
```

Then you can test it easily if you have access to a v12 instance.

``` python
from TM1py import TM1Service

with TM1Service(
        address="us-east-2.aws.planninganalytics.ibm.com",
        api_key="AB4VfG7T8wPM-912uFKeYG5PGh0XbS80MVBAt7SEG6xn",
        iam_url="https://iam.cloud.ibm.com",
        tenant="YA9A2T8BS2ZU",
        database="CWRecordsMDX") as tm1:

    print(tm1.dimensions.get_all_names())
```

**Comment by MariusWirtz** [comment]
rebased on current master and ready to be merged IMO

**Pull request merged**
