### PR TITLE
Asynchronous  execute_mdx_dataframe was added

### PR DESCRIPTION
**Pull request by vmitsenko**
New method for executing multiple MDX queries in parallel and combine the results into one dataframe. Can be used to speed up MDX queries by splitting MDX into smaller MDX subqueries. This may be one of the approaches to the issue https://github.com/cubewise-code/tm1py/issues/887

### CODE REVIEW

**Comment by MariusWirtz** [comment]
Nice work @vmitsenko 
I can confirm that this works and performs well.

please add a few small test cases and then we can merge it.

**Comment by raeldor** [comment]
Is it possible to also create an execute_view_dataframe_async?  Thanks.

**Comment by MariusWirtz** [comment]
> Is it possible to also create an execute_view_dataframe_async? Thanks.

We will look into this


As a temporary solution, you could try this:

``` python
with TM1Service(**local_params) as tm1:
    view_names = ["view1", "view2", "view3", "view4"]

    mdx_queries = [
        tm1.views.get("Sales", view_name=view_name, private=False).mdx
        for view_name
        in view_names]

    df = tm1.cells.execute_mdx_dataframe_async(mdx_queries)

    print(df.shape)
```

**Comment by raeldor** [comment]
When I try this I get the error 'Object of type MDXView is not JSON serializable'.

**Comment by raeldor** [comment]
I tried that, but I think the results returned are different because I got an error further in my code about column selection being empty.

**Comment by MariusWirtz** [comment]
> I tried that, but I think the results returned are different because I got an error about column selection must not be empty.

Yes. In MDX column selection must not be empty. 
At least one dimension must be positioned on the columns.

**Comment by vmitsenko** [comment]
> Nice work @vmitsenko I can confirm that this works and performs well.
> 
> please add a few small test cases and then we can merge it.

Hi, added some tests, let me know please if something is missing.

**Comment by MariusWirtz** [comment]
> > Nice work @vmitsenko I can confirm that this works and performs well.
> > please add a few small test cases and then we can merge it.
> 
> Hi, added some tests, let me know please if something is missing.

This looks good! Thank you

**Comment by MariusWirtz** [comment]
> Is it possible to also create an execute_view_dataframe_async? Thanks.

@raeldor 
Is this still a requirement?

I think in most cases basing your export definitions on MDX is the superior approach compared to basing your exports on existing cube views.
Did you consider moving those export definitions to MDX instead?

**Comment by raeldor** [comment]
@MariusWirtz Actually, I ended up just using tm1.views.get to get the mdx and then executing using execute_mdx_dataframe.  That seemed to work.  I didn't use your async function in the end because I thought it was an async way of bringing back a single mdx query, but it turns out that wasn't the case.  I'm already executing multiple pulls from different cubes asynchronously using python multithreading.  Appreciate the work and the follow up though, thank you.

**Pull request merged**
