### PR TITLE
A couple of small fixes for tests

### PR DESCRIPTION
**Pull request by scrambldchannel**
Hi 

Thanks for tm1py. I've been doing a bit of cross-platform testing and found a couple of little fixes to how paths are managed. Let me know what you think.

I'm still getting a few failures when running on 3.7.x on windows and Linux but think they're mostly down to issues with the server I'm testing against. I might try to refactor the tests a bit as I go.

Cheers
Alex

### CODE REVIEW

**Comment by rclapp** [comment]
We may want to explore moving to PathLib as it makes path management much easier compared to the old os libraries.

https://docs.python.org/3/library/pathlib.html

Thanks,

Ryan Clapp

**Comment by scrambldchannel** [comment]
Cool, will take a look at it, happy to contribute.

**Comment by scrambldchannel** [comment]
I added another commit to convert to using pathlib

**Comment by MariusWirtz** [comment]
Hi @scrambldchannel,

thanks for the contribution! I like it.

**Pull request merged**
