### PR TITLE
Feature/cleanup cellservice writeback changesets

### PR DESCRIPTION
**Pull request by MariusWirtz**
Finish up support for changesets and sandboxes in CellService

### CODE REVIEW

**Comment by MariusWirtz** [comment]
Fixes #463

**Comment by MariusWirtz** [comment]
@rclapp please review and approve

**Review by rclapp — COMMENTED** [review]
@rkvinoth did we implement any parallel threading for the TI based data writes?

**Comment by rclapp** [comment]
Sorry for the delay, I just got a new laptop and I have been setting it up. Looks and tests well.

**Review by rclapp — APPROVED** [review]

**Comment by rkvinoth** [comment]
> @rkvinoth did we implement any parallel threading for the TI based data writes?

we were testing it and the results are looking good with default config `worker=6`
It would be nice if we can implement it.

One thing to note is that we should raise any exception before triggering the `ThreadPoolExecutor` if not then the exceptions would go unnoticed (script will complete immediately without throwing any erros).

**Pull request merged**
