### PR TITLE
Add `proxies` arg to `TM1Service`

### PR DESCRIPTION
**Pull request by MariusWirtz**
Accept `proxies` argument in `TM1Service` constructor

@Cubewise-gtejeda 
please upgrade to this branch and test it.

```
pip uninstall tm1py
pip install https://github.com/cubewise-code/tm1py/archive/refs/heads/feature/support-proxy.zip
```

``` python
proxies = {
   'http': 'http://proxy.example.com:8080',
   'https': 'http://secureproxy.example.com:8090',
}

with TM1Service(**params, proxies=proxies) as tm1:
    print(tm1.server.get_product_version())
}
```

### CODE REVIEW

**Comment by MariusWirtz** [comment]
@Cubewise-gtejeda please try again. 

Now we pass the proxies to the requests `Session` object before the first request is made to TM1.

**Comment by Cubewise-gtejeda** [comment]
Proxies are configured in the config.ini file as such:
proxies={{"http":"http://192.168.0.10:3128"},{"https":"http://192.168.0.10:3128"}}

Still getting this error:
ValueError: No response returned from URL: 'https://cubewise.planning-analytics.ibmcloud.com/tm1/api/plansamp/api/v1/Configuration/ProductVersion/$value'. Please double check your address and port number in the URL.

Last entry in the trace:
TM1py\Services\RestService.py:252: in connect
    self._start_session(...

**Comment by Cubewise-gtejeda** [comment]
Line 191:
self._proxies = kwargs.get('proxies', None)
This is setting the value correctly.

Line 228:
        self._s = Session()
        if self._proxies:
            self._s.proxies = self._proxies
This also gets populated correctly.

**Comment by Cubewise-gtejeda** [comment]
In sessions.py from the requests package line 575:
`        proxies = proxies or {}`

proxies is empty.

**Comment by Cubewise-gtejeda** [comment]
When setting environment variables it works:

```
import os
os.environ["HTTP_PROXY"] = "http://192.168.0.10:3128"
os.environ["HTTPS_PROXY"] = "http://192.168.0.10:3128"
```

Even through the proxies in sessions.py in the requests package remains empty.
See: https://requests.readthedocs.io/en/latest/user/advanced/#proxies

**Comment by Cubewise-gtejeda** [comment]
Correction from https://github.com/cubewise-code/tm1py/pull/911#issuecomment-1527711692:
The proxies in the configuration file should be specified as below:
`proxies={"http":"http://192.168.0.10:3128","https":"http://192.168.0.10:3128"}`

**Pull request merged**
