### PR TITLE
Support MDX PROPERTIES in execute_mdx_dataframe

### PR DESCRIPTION
**Pull request by MariusWirtz**
use `display_attribute=True` and user PROPERTIES in MDX query

Related to #470

### CODE REVIEW

**Comment by MariusWirtz** [comment]
Prototype for MDX PORPERTIES support in `execute_mdx_dataframe` functions:


``` python
from TM1py import TM1Service

with TM1Service(address="", port=12354, user="admin", password="apple", ssl=True) as tm1:
    mdx = """
    SELECT
    {Tm1SubsetAll([d1])} PROPERTIES [d1].[Attribute Something] ON 0,
    {Tm1SubsetAll([d2])} PROPERTIES [d2].[Number] ON 1
    FROM [c1]
    """

    data = tm1.cells.execute_mdx_dataframe(mdx, display_attribute=True)

    print(data)
```

**Comment by rclapp** [comment]
@MariusWirtz this works, but behaves differently than the old content endpoint. When properties appear on the rows, the display_attributes replaces the element which is problematic when a query includes multiple attributes. I think the the desired behavior is to add a new column for each row property, then users could drop the original member name if desired.

For this query:
`SELECT 
      NON EMPTY 
       {[Scenario].[Scenario].[Planning]} 
      ON COLUMNS , 
      NON EMPTY 
       {[Product].[Product].[C1],[Product].[Product].[C3],[Product].[Product].[C4]} 
       DIMENSION PROPERTIES [Product].[Product].[Usage], [Product].[Product].[Reporting Name]
      ON ROWS 
    FROM [Test] `

The structure would look something like this
image

**Comment by MariusWirtz** [comment]
Thanks @rclapp. I will adjust it accordingly.

**Comment by MariusWirtz** [comment]
@rclapp I changed it accordingly. The only problem I see now is that if you don't provide `PROPERTIES` for any dimension in the MDX, it will retrieve all attributes for that dimension by default.

Do you know a "dummy" `PROPERTY` of a dimension, that users could specify in the MDX in order to avoid all attributes being loaded?

**Comment by rclapp** [comment]
Yes, you could include "DIMENSION PROPERTIES MEMBER_NAME"

It works on all axis. Ideally include attributes would be false by default. When set to true the user should have a well defined query to prevent getting too many attributes.

Sent from my mobile phone

On Feb 4, 2021 8:19 AM, Marius Wirtz <notifications@github.com> wrote:

@rclapp<https://github.com/rclapp> I changed it accordingly. The only problem I see now is that if you don't provide PROPERTIES for any dimension in the MDX, it will retrieve all attributes for that dimension by default.

Do you know a "dummy" PROPERTY of a dimension, that users could specify in the MDX in order to avoid all attributes being loaded?

-

**Comment by MariusWirtz** [comment]
Nice one. `PROPERTIES MEMBER_NAME`  does the trick.  Yes, `include_attributes` is `False` by default. 
As you say, it's up to the user now to use this feature with care.

For the `execute_mdx_dataframe_shaped`, I suggest we use a different approach and a different argument name: `display_attribute`. If it's passed as `True` we would show the (first) attribute value instead of the element name. That's also how it works in Arc and what @yyzz1010 asked for in #470.

**Comment by rclapp** [comment]
Agree 100%, Shaped frames don’t need any more complexity.

**Pull request merged**
